In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [6]:
housing_df = pd.DataFrame(housing["data"],columns=housing['feature_names'])
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [7]:
target = housing['target']
target[0:10]

array([4.526, 3.585, 3.521, 3.413, 3.422, 2.697, 2.992, 2.414, 2.267,
       2.611])

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(housing_df, target, test_size=0.2)
x_train.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
14376  6.5970      33.0  7.016736   0.953975       629.0  2.631799     32.72   
12816  3.1944       6.0  4.589404   0.947020       276.0  1.827815     38.63   
17810  6.1504      19.0  5.710452   1.079096      2196.0  3.101695     37.40   
17415  2.0161      11.0  3.823129   1.115646       504.0  3.428571     34.64   
3360   3.5536      19.0  5.742600   1.065637      2229.0  2.868726     40.36   

       Longitude  
14376    -117.25  
12816    -121.50  
17810    -121.86  
17415    -120.46  
3360     -120.71

In [10]:
y_train[0:5]

array([4.964, 1.17 , 2.684, 1.188, 1.057])

In [11]:
from sklearn.ensemble import RandomForestRegressor

model1 = RandomForestRegressor()

model1.fit(x_train, y_train)

RandomForestRegressor()

In [12]:
model1.score(x_test,y_test)

0.7954438982915679

In [13]:
y_pred = model1.predict(x_test)
y_pred[0:10]

array([1.1053   , 2.3484503, 1.86005  , 2.2267   , 1.7098801, 0.60221  ,
       2.083    , 1.58791  , 3.0591829, 0.97947  ])

In [14]:
y_test[0:10]

array([0.925, 3.208, 1.619, 2.101, 1.505, 0.616, 2.265, 1.603, 1.625,
       0.77 ])

In [15]:
len(y_pred)

4128

In [16]:
len(y_test)

4128

Note: - For Classifier we use predict as well as predict_proba