In [25]:
import numpy as np
import pandas as pd

In [27]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

## Creating DataSet

In [28]:
df = pd.DataFrame(housing['data'], columns=housing["feature_names"])
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [29]:
df["target"] =  housing['target']

df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

## Spliting DataSet for training

In [30]:
x = df.drop("target",axis=1)
x.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [31]:
y = df["target"]
y[0:5]

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: target, dtype: float64

In [33]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

x_train.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
16312   3.2889      32.0  5.061086   1.050905      2177.0  2.462670     38.00   
10726  11.0138      16.0  7.306991   1.060790       868.0  2.638298     33.64   
1098    2.3833      24.0  5.643382   1.025735       726.0  2.669118     39.59   
19005   4.8750      25.0  5.781250   1.000000        85.0  2.656250     38.31   
11482   3.8365      24.0  5.082126   1.016908      1181.0  2.852657     33.73   

       Longitude  
16312    -121.33  
10726    -117.81  
1098     -121.74  
19005    -121.93  
11482    -117.99

In [34]:
y_train.head()

16312    0.989
10726    4.421
1098     0.951
19005    2.500
11482    2.509
Name: target, dtype: float64

## Training the model

In [35]:
from sklearn.ensemble import RandomForestRegressor

model1 = RandomForestRegressor()

## Evaluation of Model

r2_squared

In [37]:
from sklearn.model_selection import cross_val_score

cv_r2_squared = cross_val_score(model1, x, y, scoring=None)

cv_r2_squared

array([0.5280047 , 0.7072726 , 0.74069483, 0.62472488, 0.67961679])

# Scoring Regression

In [38]:
print(f"The r2 squared is: {np.mean(cv_r2_squared)}")

The r2 squared is: 0.6560627595025147


neg_mean_absolute_error

In [40]:
cv_nmae = cross_val_score(model1,x,y,scoring="neg_mean_absolute_error")

cv_nmae

array([-0.54574409, -0.40538789, -0.43976983, -0.46065856, -0.47669127])

In [41]:
print(f"The negative mean absolue error is: {np.mean(cv_nmae)}")

The negative mean absolue error is: -0.465650326637597


neg_mean_squared_error

In [42]:
cv_nmse = cross_val_score(model1,x,y,scoring="neg_mean_squared_error")

cv_nmse

array([-0.51669795, -0.34697942, -0.37111325, -0.44637   , -0.46711543])

In [43]:
print(f"The negative mean square error is: {np.mean(cv_nmse)}")

The negative mean square error is: -0.4296552092435599
