# Evaluation of Regression Model

We will see only 3 types of it:-

1. R-squared
2. Mean absolute error
3. Mean squared error

## Training the model for Evaluation

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Getting the dataset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [4]:
x = pd.DataFrame(housing["data"],columns=housing["feature_names"])
x.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [5]:
y = housing["target"]

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

x_train.head(),y_train[0:5]

(       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 13907  2.4828      17.0  5.446618   1.056235      2677.0  2.181744     34.10   
 9320   2.5125      52.0  3.723150   1.076372       700.0  1.670644     37.97   
 15852  3.8846      52.0  5.305835   1.084507      1159.0  2.331992     37.74   
 16644  6.3144      28.0  6.921191   1.036778      1469.0  2.572680     35.28   
 8808   7.5594      18.0  5.232456   1.021930       475.0  2.083333     33.71   
 
        Longitude  
 13907    -116.43  
 9320     -122.53  
 15852    -122.43  
 16644    -120.62  
 8808     -118.39  ,
 array([0.84   , 2.708  , 3.331  , 3.288  , 5.00001]))

In [7]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(x_train,y_train)

RandomForestRegressor()

In [8]:
model.score(x_test,y_test)

0.8169771954183043

Mean absolute error: - It tells the average of absolute difference between actual value and predicted value.

In [9]:
from sklearn.metrics import mean_absolute_error

y_pred = model.predict(x_test)
y_pred[0:10]

array([0.75091  , 2.1453004, 2.08151  , 0.79113  , 2.5599802, 0.7341   ,
       2.3442   , 1.47417  , 0.85421  , 2.82186  ])

In [10]:
y_test[0:10]

array([0.89 , 1.908, 3.244, 0.875, 2.954, 0.633, 2.356, 1.254, 0.973,
       2.887])

In [11]:
mean_absolute_error(y_test,y_pred)

0.3247690992974807

Mean squared error: - It is the mean of the sqaure of the errors between actual and predicted values.

In [12]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test,y_pred)

0.24299844411048757