# Cross Validation Score

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [2]:
# Training the data

df = pd.read_csv("heart-disease.csv")

df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
x = df.drop("target",axis=1)

x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [4]:
y = df["target"]

In [5]:
y[0:5]

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [6]:
clf = RandomForestClassifier()

Finding cross_val_score

In [7]:
cro_val = cross_val_score(clf,x,y,cv=5)

In [8]:
cro_val

array([0.81967213, 0.90163934, 0.80327869, 0.81666667, 0.76666667])

In [12]:
print(f"The cross validation score is: {np.mean(cro_val)*100:.2f}%")

The cross validation score is: 82.16%


Using accuracy

In [15]:
cv_acc = cross_val_score(clf,x,y,cv=5,scoring="accuracy")
cv_acc

array([0.83606557, 0.85245902, 0.81967213, 0.81666667, 0.78333333])

In [16]:
print(f"The cross validation accuracy is: {np.mean(cv_acc)*100:.2f}%")

The cross validation accuracy is: 82.16%


Using Precision

In [17]:
cv_pre = cross_val_score(clf,x,y,cv=5,scoring="precision")
cv_pre

array([0.82857143, 0.90625   , 0.78125   , 0.84848485, 0.76923077])

In [23]:
print(f"The cross validation precision is: {np.mean(cv_pre)}")

The cross validation precision is: 0.8267574092574094


Using recall

In [19]:
cv_re = cross_val_score(clf,x,y,cv=5,scoring="recall")
cv_re


array([0.93939394, 0.84848485, 0.78787879, 0.81818182, 0.90909091])

In [24]:
print(f"The cross validation recall is: {np.mean(cv_re)}")

The cross validation recall is: 0.8606060606060607
